# Generated by Django 4.0.4 on 2022-05-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
